### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Zachary1Taylor** [Zachary1Taylor/near-riddles#1]
- [ ] Rust合约 @Zachary1Taylor @GopherJ @veneris 
- [ ] 单元测试  @Zachary1Taylor @GopherJ 
- [ ] 模拟测试 @Jackieyewang 
- [ ] 文档 @veneris 
- [ ] UI/UX设计 @Jackieyewang 
- [ ] 演示

**Comment by GopherJ** [comment]
项目目地: **实现任意类型的资产交换**

设计重点:
                    中间人
                       |
卖方 <------ |合约| ------> 买方
1. 任何财产足够多的账户都可以注册成为中间人

**Comment by 0x8f701** [comment]
具体设计:

1.  riddle 应该包含难度系数, 并且最好设置每个人最多答三次，难度系数用于前端显示
2.  riddle 应该包含领域, 方便前端处理页面, 让人们可以选择领域作答
3.  riddle 应该有个期限, 期限过了应该将钱退回创建者 (可选)
4.  riddle 应该包含like, dislike次数 (可选)
5.  riddle 可以考虑有提示语 (可选)
6.  riddle 的领域感觉应该提前确定, 否则创建人可以指定, "Science", "科学"... "科 学"
7.  riddle 的语言感觉也应该跟 domain 一个级别 (可选) 方便选择语言做答
